name: CI Event Service

on:
  push:
    branches:
      - dev
      - main
    paths:
      - event-service/**
      - .github/workflows/ci-template.yml
      - .github/workflows/ci-event-service.yml
  workflow_dispatch:

permissions:
  contents: write
  id-token: write

jobs:
  ci:
    uses: ./.github/workflows/ci-template.yml
    with:
      service_name: event-service
      service_path: event-service
      ecr_repository: blacktickets-event-service
    secrets: inherit
